USE VEHDB


-- Q1
SELECT COUNT(CUSTOMER_ID) AS TOTAL_NUMBER_OF_CUSTOMERS
FROM CUSTOMER_T;

SELECT STATE,COUNT(CUSTOMER_ID) AS NO_OF_CUSTOMERS
FROM CUSTOMER_T
GROUP BY STATE;


--Q2
SELECT PRODUCT.VEHICLE_MAKER, COUNT(ORDERS.ORDER_ID) AS ORDERS
FROM PRODUCT_T AS PRODUCT INNER JOIN
ORDER_T AS ORDERS
ON PRODUCT.PRODUCT_ID = ORDERS.PRODUCT_ID
GROUP BY PRODUCT.VEHICLE_MAKER
ORDER BY ORDERS DESC
LIMIT 5;

--Q3
SELECT  RANKING_TABLE.STATE,RANKING_TABLE.VEHICLE_MAKER, RANKING_TABLE.CUSTOMER_COUNT
FROM (
    SELECT COMBINED_TABLE.STATE,COMBINED_TABLE.VEHICLE_MAKER, COMBINED_TABLE.CUSTOMER_COUNT,
    RANK() OVER (PARTITION BY COMBINED_TABLE.STATE ORDER BY COMBINED_TABLE.CUSTOMER_COUNT DESC) AS MAKER_RANK
    FROM (
          SELECT CUSTOMERS.STATE, PRODUCTS.VEHICLE_MAKER, COUNT (DISTINCT ORDERS.CUSTOMER_ID) AS CUSTOMER_COUNT
          FROM ORDER_T AS ORDERS 
          INNER JOIN CUSTOMER_T AS CUSTOMERS  ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
          INNER  JOIN PRODUCT_T AS  PRODUCTS ON PRODUCTS.PRODUCT_ID = ORDERS.PRODUCT_ID
          GROUP BY CUSTOMERS.STATE, PRODUCTS.VEHICLE_MAKER
    )  AS COMBINED_TABLE
) AS RANKING_TABLE
WHERE MAKER_RANK = 1;

--Q4
SELECT RATING_TABLE.QUARTER_NUMBER, AVG(RATING_TABLE.RATING) AS AVERAGE_RATING
FROM (
          SELECT QUARTER_NUMBER, 
          CASE CUSTOMER_FEEDBACK
           WHEN 'Very Bad' THEN 1
            WHEN 'Bad' THEN 2
            WHEN 'Okay' THEN 3
            WHEN 'Good' THEN 4
            WHEN 'Very Good' THEN 5
          END AS RATING
          FROM ORDER_T 
        ) AS RATING_TABLE
GROUP BY RATING_TABLE.QUARTER_NUMBER
ORDER BY RATING_TABLE.QUARTER_NUMBER;


--Q5
SELECT 
    QUARTER_NUMBER,
    SUM(CASE WHEN CUSTOMER_FEEDBACK = 'Very Bad' THEN 1 ELSE 0 END) / COUNT(CUSTOMER_FEEDBACK)*100 AS VERY_BAD_PERCENTAGE,
    SUM(CASE WHEN CUSTOMER_FEEDBACK = 'Bad' THEN 1 ELSE 0 END) / COUNT(CUSTOMER_FEEDBACK)*100 AS BAD_PERCENTAGE,
    SUM(CASE WHEN CUSTOMER_FEEDBACK = 'Okay' THEN 1 ELSE 0 END) / COUNT(CUSTOMER_FEEDBACK)*100 AS OKAY_PERCENTAGE,
    SUM(CASE WHEN CUSTOMER_FEEDBACK = 'Good' THEN 1 ELSE 0 END) / COUNT(CUSTOMER_FEEDBACK)*100 AS GOOD_PERCENTAGE,
    SUM(CASE WHEN CUSTOMER_FEEDBACK = 'Very Good' THEN 1 ELSE 0 END) / COUNT(CUSTOMER_FEEDBACK)*100 AS VERY_GOOD_PERCENTAGE
FROM ORDER_T
GROUP BY QUARTER_NUMBER
ORDER BY QUARTER_NUMBER;


--Q6
SELECT QUARTER_NUMBER, COUNT(ORDER_ID) AS ORDERS
FROM ORDER_T
GROUP BY QUARTER_NUMBER
ORDER BY QUARTER_NUMBER;

--Q7
SELECT REVENUE_TABLE.QUARTER_NUMBER, REVENUE_TABLE.NET_REVENUE, ((REVENUE_TABLE.NET_REVENUE - REVENUE_TABLE.PREV_REVENUE) / REVENUE_TABLE.PREV_REVENUE)*100 AS QoQ_PERCENTAGE_CHANGE
FROM (
      SELECT REVENUE_PER_QUARTER.QUARTER_NUMBER, REVENUE_PER_QUARTER.NET_REVENUE, 
      LAG(REVENUE_PER_QUARTER.NET_REVENUE) OVER ( ORDER BY REVENUE_PER_QUARTER.QUARTER_NUMBER) AS PREV_REVENUE
      FROM (
                SELECT ORDERS.QUARTER_NUMBER, SUM((ORDERS.QUANTITY *ORDERS.VEHICLE_PRICE) - ORDERS.DISCOUNT) AS NET_REVENUE
                FROM ORDER_T AS ORDERS
                GROUP BY QUARTER_NUMBER
      )  AS REVENUE_PER_QUARTER
)AS REVENUE_TABLE
ORDER BY QUARTER_NUMBER

--Q8
SELECT QUARTER_NUMBER, 
((SUM((QUANTITY * VEHICLE_PRICE) - DISCOUNT)) / (SELECT SUM((QUANTITY*VEHICLE_PRICE) - DISCOUNT)FROM ORDER_T)) * 100 AS NET_REVENUE_PERCENTAGE, 
COUNT(ORDER_ID) AS ORDERS 
FROM ORDER_T
GROUP BY QUARTER_NUMBER
ORDER BY QUARTER_NUMBER;

--Q9
SELECT ORDERS_CUSTOMERS.CREDIT_CARD_TYPE, AVG(ORDERS_CUSTOMERS.DISCOUNT) AS AVERAGE_DISCOUNT
FROM 
(SELECT CUSTOMERS.CREDIT_CARD_TYPE, ORDERS.DISCOUNT  FROM ORDER_T AS ORDERS INNER JOIN CUSTOMER_T AS CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID) AS ORDERS_CUSTOMERS
GROUP BY ORDERS_CUSTOMERS.CREDIT_CARD_TYPE
ORDER BY AVERAGE_DISCOUNT DESC;


--Q10
SELECT QUARTER_NUMBER, AVG(DATEDIFF(SHIP_DATE,ORDER_DATE)) AS AVERAGE_TIME_TAKEN_TO_SHIP
FROM ORDER_T
GROUP BY QUARTER_NUMBER
ORDER BY QUARTER_NUMBER;

--total_revenue
SELECT SUM((QUANTITY*VEHICLE_PRICE) - DISCOUNT) AS TOTAL_NET_REVENUE FROM ORDER_T

--total_orders
SELECT COUNT(ORDER_ID) FROM ORDER_T

--total_customers
SELECT COUNT(CUSTOMER_ID) FROM CUSTOMER_T

--avg_rating
SELECT AVG(RATING_TABLE.RATING) AS OVERALL_AVERAGE_RATING
FROM (
          			SELECT QUARTER_NUMBER, 
          			CASE CUSTOMER_FEEDBACK
           			WHEN 'Very Bad' THEN 1
           			WHEN 'Bad' THEN 2
           			WHEN 'Okay' THEN 3
            			WHEN 'Good' THEN 4
            			WHEN 'Very Good' THEN 5
          			END AS RATING
          			FROM ORDER_T 
        		) AS RATING_TABLE;


--last_quarter_revenue
SELECT SUM((QUANTITY*VEHICLE_PRICE) - DISCOUNT)FROM ORDER_T
WHERE QUARTER_NUMBER = 4

--last_quarter_order
SELECT COUNT(ORDER_ID) FROM ORDER_T
WHERE QUARTER_NUMBER =4

--avg_days_ship
SELECT AVG(DATEDIFF(SHIP_DATE,ORDER_DATE)) FROM ORDER_T

--percentage_good_feedback
SELECT 
  (COUNT(CASE WHEN CUSTOMER_FEEDBACK = 'Good' THEN 1 END) * 100.0) / COUNT(*) AS good_feedback_percentage
FROM ORDER_T;